name: Generar Mi APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install flet requests

      - name: Compilar APK
        run: |
          flet build apk --filename MiAgenda2026.apk

      - name: Subir Resultado
        uses: actions/upload-artifact@v4
        with:
          name: MiAppInstalable
          path: build/apk/*.apk
