name: BuildAPK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install flet requests
      - name: Build APK
        run: |
          # El comando 'yes' le dice que SI a todas las preguntas de instalacion
          yes | flet build apk
      - uses: actions/upload-artifact@v4
        with:
          name: AppInstalable
          path: build/apk/*.apk
